<?php

return [
    'box_limit' => 3,
    'box_name' => "Coder's Hot Sauce Box",
    'box_unit_amount' => 1999,
    'stripe_box_price_id' => env('STRIPE_BOX_PRICE_ID', 'price_default_box'),
    'products' => [
        [
            'slug' => 'coders-hot-classic',
            'name' => "Coder's Hot Classic",
            'tagline' => 'Scotch bonnet vinegar and rock salt snap for dependable pizza heat.',
            'description' => 'The core bottle. Bright, savory, and balanced enough to live on every desk-side Friday slice.',
            'heat_label' => 'Hot',
            'taste_label' => 'Classic',
            'heat_level' => 4,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_CLASSIC_HOT'),
            'accent' => '#f97316',
            'glow' => 'rgba(249, 115, 22, 0.45)',
            'image' => '/images/products/coders-classic-hot-sauce.png',
            'can_sell' => true,
            'can_be_built' => true,
            'can_build_with' => false
        ],
        [
            'slug' => 'coders-hot-mango',
            'name' => "Coder's Hot Mango",
            'tagline' => 'Mango sweetness, chilli bite, and a clean tropical finish.',
            'description' => 'Built for smoky crust and pepperoni edges. Sweet enough to round the heat, sharp enough to stay professional.',
            'heat_label' => 'Hot',
            'taste_label' => 'Mango',
            'heat_level' => 4,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_MANGO_HOT'),
            'accent' => '#fb923c',
            'glow' => 'rgba(251, 146, 60, 0.42)',
            'image' => '/images/products/coders-mango-hot-sauce.png',
            'can_sell' => true,
            'can_be_built' => true,
            'can_build_with' => false
        ],
        [
            'slug' => 'coders-hot-honey',
            'name' => "Coder's Hot Honey",
            'tagline' => 'Wildflower honey, strong heat, and just enough sting for a proper fold.',
            'description' => 'Sticky in the right way. Made for crust drizzles, cheese slices, and late-night pizza that needs a sharper finish.',
            'heat_label' => 'Hot',
            'taste_label' => 'Honey',
            'heat_level' => 4,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_HONEY_HOT'),
            'accent' => '#facc15',
            'glow' => 'rgba(250, 204, 21, 0.35)',
            'image' => '/images/products/coders-honey-hot-sauce.png',
            'can_sell' => true,
            'can_be_built' => true,
            'can_build_with' => false
        ],
        [
            'slug' => 'coders-hot-chocolate',
            'name' => "Coder's Hot Chocolate",
            'tagline' => 'Dark chocolate, deep chili, and a slower heat built for deep crust nights.',
            'description' => 'The moodier bottle. Rich, smoky, and sharp enough to work with sausage pizza and charred crust.',
            'heat_label' => 'Hot',
            'taste_label' => 'Chocolate',
            'heat_level' => 4,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1700,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_CHOCOLATE_HOT'),
            'accent' => '#f87171',
            'glow' => 'rgba(248, 113, 113, 0.34)',
            'image' => '/images/products/coders-chocolate-hot-sauce.png',
            'can_sell' => true,
            'can_be_built' => true,
            'can_build_with' => false
        ],
    ],
    'merch_products' => [
        // Provisions for branded merch details to follow
    ],
];
