<?php

return [
    'box_limit' => 3,
    'box_name' => "Coder's Hot Sauce Box",
    'box_unit_amount' => 1999,
    'stripe_box_price_id' => env('STRIPE_BOX_PRICE_ID', 'price_default_box'),
    'products' => [
        [
            'slug' => 'coders-hot-classic',
            'name' => "Coder's Hot Classic",
            'tagline' => 'Red jalapeno, garlic, and vinegar snap for dependable pizza heat.',
            'description' => 'The core bottle. Bright, savory, and balanced enough to live on every desk-side Friday slice.',
            'heat_label' => 'Classic Heat',
            'heat_level' => 3,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_CLASSIC_HOT'),
            'accent' => '#f97316',
            'glow' => 'rgba(249, 115, 22, 0.45)',
        ],
        [
            'slug' => 'coders-hot-mango',
            'name' => "Coder's Hot Mango",
            'tagline' => 'Mango sweetness, habanero bite, and a clean tropical finish.',
            'description' => 'Built for smoky crust and pepperoni edges. Sweet enough to round the heat, sharp enough to stay professional.',
            'heat_label' => 'Mango Lift',
            'heat_level' => 2,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_MANGO_HOT'),
            'accent' => '#fb923c',
            'glow' => 'rgba(251, 146, 60, 0.42)',
        ],
        [
            'slug' => 'coders-hot-honey',
            'name' => "Coder's Hot Honey",
            'tagline' => 'Wildflower honey, chili heat, and just enough sting for a proper fold.',
            'description' => 'Sticky in the right way. Made for crust drizzles, cheese slices, and late-night pizza that needs a sharper finish.',
            'heat_label' => 'Honey Burn',
            'heat_level' => 4,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_HONEY_HOT'),
            'accent' => '#facc15',
            'glow' => 'rgba(250, 204, 21, 0.35)',
        ],
        [
            'slug' => 'coders-hot-chocolate',
            'name' => "Coder's Hot Chocolate",
            'tagline' => 'Dark cocoa, smoked chili, and a slower heat built for deep crust nights.',
            'description' => 'The moodier bottle. Rich, smoky, and sharp enough to work with sausage pizza and charred crust.',
            'heat_label' => 'Midnight Burn',
            'heat_level' => 5,
            'price' => 6,
            'currency' => 'gbp',
            'unit_amount' => 1700,
            'size_label' => '125ml bottle',
            'stripe_product_id' => env('STRIPE_CODERS_CHOCOLATE_HOT'),
            'accent' => '#f87171',
            'glow' => 'rgba(248, 113, 113, 0.34)',
        ],
    ],
    'merch_products' => [
        // Provisions for branded merch details to follow
    ],
];
